#pragma once

// ===== Default Library =====
#include <array>
#include <mutex>
#include <cstdint>
#include <algorithm>
#include <unordered_map>
#include <cstdarg>
#include <string>
#include <string_view>
#include <vector>

#include <string.h>

// ===== SKSE =====
#include <SKSE/Logger.h>

// ===== RE (Game Types) =====
#include <RE/Offsets_VTABLE.h>
#include <REL/Relocation.h>
#include <REL/Module.h>

#include <RE/A/Actor.h>
#include <RE/A/ActorState.h>
#include <RE/A/ActorValues.h>
#include <RE/A/AlchemyItem.h>

#include <RE/B/BSTEvent.h>
#include <RE/B/BSContainer.h>
#include <RE/B/BSFixedString.h>
#include <RE/B/BGSKeywordForm.h>
#include <RE/B/BGSBipedObjectForm.h>
#include <RE/B/BSPointerHandle.h>
#include <RE/B/BSCoreTypes.h>
#include <RE/B/BarterMenu.h>
#include <RE/B/ButtonEvent.h>

#include <RE/C/ContainerMenu.h>
#include <RE/C/CraftingMenu.h>
#include <RE/C/CrosshairPickData.h>

#include <RE/E/ExtraAshPileRef.h>
#include <RE/E/ExtraDataTypes.h>

#include <RE/F/FavoritesMenu.h>
#include <RE/F/FormTypes.h>

#include <RE/G/GiftMenu.h>

#include <RE/I/IngredientItem.h>
#include <RE/I/InputEvent.h>
#include <RE/I/InputDevices.h>

#include <RE/M/MagicMenu.h>

#include <RE/N/NiSmartPointer.h>

#include <RE/I/InventoryEntryData.h>
#include <RE/I/InventoryMenu.h>

#include <RE/P/PlayerCharacter.h>
#include <RE/P/ProcessLists.h>

#include <RE/S/ScrollItem.h>
#include <RE/S/SendHUDMessage.h>

#include <RE/T/TESBoundObject.h>
#include <RE/T/TESObjectREFR.h>
#include <RE/T/TESContainer.h>
#include <RE/T/TESEnchantableForm.h>
#include <RE/T/TESObjectMISC.h>
#include <RE/T/TESObjectARMO.h>
#include <RE/T/TESObjectWEAP.h>
#include <RE/T/TESObjectBOOK.h>
#include <RE/T/TESAmmo.h>

#include <RE/U/UI.h>

// ===== APIs =====
#include "QuickLootAPI.h"

// ===== Project =====
#include "DeathTracker.h"
#include "JunkIt.h"
#include "Settings.h"
#include "ToolRequirements.h"
#include "Translation.h"

namespace LootHook
{
    using GetPlayable_t = bool(*)(RE::TESBoundObject*);
    inline REL::Relocation<GetPlayable_t> original_ARMO_GetPlayable;
    inline REL::Relocation<GetPlayable_t> original_WEAP_GetPlayable;
    inline REL::Relocation<GetPlayable_t> original_MISC_GetPlayable;
    inline REL::Relocation<GetPlayable_t> original_ALCH_GetPlayable;
    inline REL::Relocation<GetPlayable_t> original_INGR_GetPlayable;
    inline REL::Relocation<GetPlayable_t> original_BOOK_GetPlayable;
    inline REL::Relocation<GetPlayable_t> original_SCRL_GetPlayable;
    inline REL::Relocation<GetPlayable_t> original_AMMO_GetPlayable;

	// Listens for hotkey presses to toggle the mod on/off
    class InputListener : public RE::BSTEventSink<RE::InputEvent*> {
    public:
        static InputListener* GetSingleton() {
            static InputListener singleton;
            return &singleton;
        }

        // Processes all input events generated by the game engine every frame
        virtual RE::BSEventNotifyControl ProcessEvent(RE::InputEvent* const* a_event, RE::BSTEventSource<RE::InputEvent*>*) override {
            // Abort if there are no events or if the hotkey feature is disabled in the settings
            if (!a_event || !*a_event || !Settings::bEnableHotkey) return RE::BSEventNotifyControl::kContinue;

            for (auto event = *a_event; event; event = event->next) {
                if (event->GetEventType() == RE::INPUT_EVENT_TYPE::kButton) {
                    auto button = event->AsButtonEvent();
                    if (button && button->GetDevice() == RE::INPUT_DEVICE::kKeyboard) {
                        auto key = button->GetIDCode();

                        // Track modifier key state
                        if (key == static_cast<uint32_t>(Settings::iToggleModifierKey)) {
                            _modifierHeld = button->IsPressed();
                        }
                        // Check for main hotkey press
                        else if (key == static_cast<uint32_t>(Settings::iToggleHotkey) && button->IsDown()) {
                            bool modifierConditionMet = (Settings::iToggleModifierKey == 0) || _modifierHeld;
                            if (modifierConditionMet) {
                                Settings::bEnableMod = !Settings::bEnableMod;
                                if (Settings::bEnableMod) {
                                    RE::SendHUDMessage::ShowHUDMessage(Translation::Get("$HL_HUD_Enabled", "Hidden Loot: Enabled").c_str());
                                }
                                else {
                                    RE::SendHUDMessage::ShowHUDMessage(Translation::Get("$HL_HUD_Disabled", "Hidden Loot: Disabled").c_str());
                                }
                            }
                        }
                    }
                }
            }
            return RE::BSEventNotifyControl::kContinue;
        }
    private:
        InputListener() = default;

        // Remembers if the modifier key is currently held down across frames
        bool _modifierHeld = false;
    };

    // Helper to check if a specific item exists in a reference's inventory (Base or Dynamic)
    bool ContainerHasItem(RE::TESObjectREFR* a_ref, RE::TESBoundObject* a_item, bool a_allowShortcut)
    {
        if (!a_ref || !a_item) return false;

        auto base = a_ref->GetBaseObject();
        if (!base) return false;

        // Check dynamic inventory changes (worn, added via scripts, or moved items)
        auto changes = a_ref->GetInventoryChanges();
        if (changes && changes->entryList) {
            for (auto* entry : *changes->entryList) {
                if (entry && entry->object && entry->object->GetFormID() == a_item->GetFormID()) {
                    if (a_ref->IsPlayerRef()) {
                        // Protect against false-positives for items the player just dropped/lost
                        if (entry->countDelta > 0) return true;
                    }
                    else {
                        return true;
                    }
                }
            }
        }

        // Check base container data (default loot defined in ESP/ESM that hasn't been instantiated yet)
        auto container = base->As<RE::TESContainer>();
        if (container) {
            bool found = false;
            container->ForEachContainerObject([&](RE::ContainerObject& a_obj) {
                if (a_obj.obj && a_obj.obj->GetFormID() == a_item->GetFormID()) {
                    found = true;
                    return RE::BSContainer::ForEachResult::kStop;
                }
                return RE::BSContainer::ForEachResult::kContinue;
                });
            if (found) return true;
        }

        // Skip the item scan for activators/special container (e.g. Ash Piles)
        if (a_allowShortcut) {
            bool isActivator = base->Is(RE::FormType::Activator);
            bool isDynamicContainer = base->Is(RE::FormType::Container) && ((a_ref->GetFormID() >> 24) == 0xFF);
            if (isActivator || isDynamicContainer) return true;
        }

        return false;
    }

    // Crosshair retrieval to allow vanilla Skyrim to correctly display the "(Empty)" prompt when looking at a corpse where all items are hidden by the mod
    RE::TESObjectREFR* GetCrosshairTarget(RE::TESBoundObject* a_item)
    {
        auto crosshair = RE::CrosshairPickData::GetSingleton();
        if (!crosshair) return nullptr;

        RE::NiPointer<RE::TESObjectREFR> refPtr;

        // Handle Skyrim VR specific crosshair/hand targeting
        if (REL::Module::IsVR()) {
            const auto player = RE::PlayerCharacter::GetSingleton();
            if (player) {
                const auto& vrData = player->GetVRPlayerRuntimeData();
                const uint32_t mainHand = vrData->isRightHandMainHand ? 1 : 0;
                const uint32_t offHand = vrData->isRightHandMainHand ? 0 : 1;

                if (crosshair->grabPickRef[mainHand]) refPtr = crosshair->grabPickRef[mainHand].get();
                else if (crosshair->grabPickRef[offHand]) refPtr = crosshair->grabPickRef[offHand].get();

                else if (crosshair->targetActor[mainHand]) refPtr = crosshair->targetActor[mainHand].get();
                else if (crosshair->targetActor[offHand]) refPtr = crosshair->targetActor[offHand].get();

                else if (crosshair->target[mainHand]) refPtr = crosshair->target[mainHand].get();
                else if (crosshair->target[offHand]) refPtr = crosshair->target[offHand].get();
            }
        }
        else {
            // Skyrim SE/AE targeting
            if (crosshair->target[0]) refPtr = crosshair->target[0].get();
        }

        RE::TESObjectREFR* target = refPtr.get();
        if (!target) return nullptr;

        // Does the target the player is looking at actually own this item?
        auto base = target->GetBaseObject();
        bool isSpecial = base && (base->Is(RE::FormType::Activator) || (base->Is(RE::FormType::Container) && (target->GetFormID() >> 24) == 0xFF));

        if (ContainerHasItem(target, a_item, isSpecial)) {
            return target;
        }

        return nullptr;
    }

	// Core logic to determine if an item should be hidden based on the current game state, player state, and item properties
    bool ShouldHideItem(RE::TESBoundObject* a_item, RE::TESObjectREFR* a_targetRef, bool a_isContainerOpen, bool a_isLootMenuOpen, RE::InventoryEntryData* a_entryData = nullptr)
    {
        if (!a_item || !a_targetRef) return false;

        auto player = RE::PlayerCharacter::GetSingleton();
        bool isPlayerLoaded = player && player->Is3DLoaded();

        // Absolute safety nets for Lockpicks - never hide them
        auto formID = a_item->GetFormID();
        if (formID == 0x0000000A) return false;

        // Safety net for Gold (bypassed if user explicitly enables hiding gold)
        if (formID == 0x0000000F && !Settings::bHideGold) return false;

        // Never hide Gems
        auto kwForm = a_item->As<RE::BGSKeywordForm>();
        if (kwForm && kwForm->HasKeywordString("VendorItemGem")) return false;

        // Item whitelist priority: If the item has any of the user-defined whitelist keywords, it should always be shown regardless of other settings
        if (!Settings::whitelistedItemBaseIDs.empty()) {
            auto itemFormID = a_item->GetFormID();
            if (std::binary_search(Settings::whitelistedItemBaseIDs.begin(), Settings::whitelistedItemBaseIDs.end(), itemFormID)) {
                return false;
            }
        }

        // Mod specific whitelist checks
        if (auto file = a_item->GetFile(0)) {
            const char* modName = file->GetFilename().data();

            auto CompareModName = [&](const std::string& listName) {
                return _stricmp(modName, listName.c_str()) == 0;
                };

            if (!Settings::whitelistedModsList.empty()) {
                if (std::find_if(Settings::whitelistedModsList.begin(), Settings::whitelistedModsList.end(), CompareModName) != Settings::whitelistedModsList.end()) {
                    return false;
                }
            }
        }

        // Helper to check if the item has any keyword from a given list
        auto HasKeywordFromList = [&](const std::vector<RE::BSFixedString>& keywordList) -> bool {
            if (keywordList.empty()) return false;
            auto kwForm = a_item->As<RE::BGSKeywordForm>();
            if (kwForm) {
                for (const auto& kw : keywordList) {
                    if (kwForm->HasKeywordString(kw)) return true;
                }
            }
            return false;
        };

        bool isAmmo = a_item->IsAmmo();
        bool isClutter = !a_item->IsWeapon() && !a_item->IsArmor() && !isAmmo;
        float currentHideChance = Settings::fHideChance;
        bool shouldHide = false;
        bool requireWorn = true;

        // variable for skill scaling
        RE::ActorValue associatedSkill = RE::ActorValue::kNone;
        bool isSmithable = false;

        // Check if any item is marked by Junk It as junk
        bool isJunkItCandidate = false;
        if (Settings::bHideJunkItItems && JunkIt::API) {
            if (JunkIt::API->IsAnyJunkForForm(a_item)) {
                isJunkItCandidate = true;
            }
        }

        // Tool Requirements Check
        bool isToolCandidate = false;
        if (Settings::bEnableToolRequirements) {
            isToolCandidate = ToolRequirements::Manager::GetSingleton()->IsLootCandidate(a_item);
        }

        // Check Blacklists first
        bool isBlacklisted = false;
        if (auto file = a_item->GetFile(0)) {
            const char* modName = file->GetFilename().data();
            auto CompareModName = [&](const std::string& listName) {
                return _stricmp(modName, listName.c_str()) == 0;
                };

            if (std::find_if(Settings::blacklistedModsList.begin(), Settings::blacklistedModsList.end(), CompareModName) != Settings::blacklistedModsList.end()) {
                isBlacklisted = true;
            }
        }
        if (!isBlacklisted && HasKeywordFromList(Settings::hideKeywordsList)) {
            isBlacklisted = true;
        }

        // Apply logic based on item type
        if (isBlacklisted) {
            shouldHide = true;
            requireWorn = false;

            // Force hide regardless of sliders
            currentHideChance = 100.0f;
        }
        else if (isClutter) {
            bool isGold = (formID == 0x0000000F);
            bool isMiscBlacklisted = HasKeywordFromList(Settings::miscHideKeywordsList);

            // If the misc item isn't specifically blacklisted, isn't gold, and is neither a Junk It nor Tool Requirement candidate, show it
            if (!isMiscBlacklisted && !isJunkItCandidate && !isToolCandidate && !isGold) return false;

            // Only set to shouldHide if it is actually blacklisted by the user!
            if (isMiscBlacklisted) {
                shouldHide = true;
                currentHideChance = Settings::fHideChanceMisc;
            }
            else if (isGold) {
                shouldHide = true;
                currentHideChance = Settings::fHideChanceGold;
            }

            // Clutter items are never worn
            requireWorn = false;
            associatedSkill = RE::ActorValue::kPickpocket;
        }
        else {
            // Special handling for backpacks - armor/clothing with ModBack slot (47)
            bool isBackpack = false;
            if (a_item->IsArmor()) {
                auto armor = static_cast<RE::TESObjectARMO*>(a_item);
                if (armor->GetSlotMask().any(RE::BIPED_MODEL::BipedObjectSlot::kModBack)) {
                    isBackpack = true;
                }
            }

            // Static whitelists: Items above value threshold or with specific keywords (uniques, artifacts, etc.) are always lootable (skip if it's a backpack)
            if (!isBackpack) {
                // Check if the item is a Junk It or missing tool candidate. If neither, it may be whitelisted based on value or keywords.
                if (!isJunkItCandidate && !isToolCandidate) {
                    // value/weight threshold
                    if (Settings::fValueWeightThresholdForLoot > 0.0f) {
                        float weight = a_item->GetWeight();
                        float valWeight = (weight > 0.0f) ? (a_item->GetGoldValue() / weight) : (a_item->GetGoldValue() > 0 ? 999999.0f : 0.0f);
                        if (valWeight >= Settings::fValueWeightThresholdForLoot) return false;
                    }

                    // value threshold
                    if (a_item->GetGoldValue() >= Settings::fValueThresholdForLoot) return false;
                    if (a_item->HasKeywordInArray(Settings::uniqueKeywords, false)) return false;
                }
            }

            // Option: Whitelist all naturally enchanted items (skip if it's a backpack, or a Junk It or missing tool candidate)
            if (Settings::bAlwaysShowEnchanted && !isBackpack && !isJunkItCandidate && !isToolCandidate) {
                auto enchantable = a_item->As<RE::TESEnchantableForm>();
                if (enchantable && enchantable->formEnchanting) return false;
            }

            // Category detection (Armor, Weapon, Clothing, Jewelry)
            bool isWeapon = a_item->IsWeapon();
            bool isArmor = false, isClothing = false, isJewelry = false;
            bool isHead = false, isChest = false, isArms = false, isLegs = false, isShield = false;

            // Categorize armor types and body slots (skip if it's a backpack)
            if (a_item->IsArmor() && !isBackpack) {
                auto armor = static_cast<RE::TESObjectARMO*>(a_item);
                auto CheckSlot = [&](RE::BIPED_MODEL::BipedObjectSlot a_slot) -> bool {
                    return armor->GetSlotMask().any(a_slot);
                };

                // Differentiate between generic clothing/armor and Jewelry (Rings/Amulets)
                if (CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kAmulet) ||
                    CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kRing)) {
                    isJewelry = true;
                }
                else {
                    // Categorize by body slots for granular control
                    isHead = CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kHead) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kHair) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kCirclet);

                    isChest = CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kBody) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kModChestPrimary) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kModChestSecondary);

                    isArms = CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kHands) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kForearms) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kModShoulder) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kModArmLeft) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kModArmRight);

                    isLegs = CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kFeet) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kCalves) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kModPelvisPrimary) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kModPelvisSecondary) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kModLegLeft) ||
                        CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kModLegRight);

                    isShield = CheckSlot(RE::BIPED_MODEL::BipedObjectSlot::kShield);

                    if (armor->GetArmorType() == RE::BIPED_MODEL::ArmorType::kClothing) {
                        isClothing = true;
                    }
                    else {
                        isArmor = true;
                    }
                }
                if (isShield) {
                    associatedSkill = RE::ActorValue::kBlock;
                }
                else if (armor->GetArmorType() == RE::BIPED_MODEL::ArmorType::kLightArmor) {
                    associatedSkill = RE::ActorValue::kLightArmor;
                }
                else if (armor->GetArmorType() == RE::BIPED_MODEL::ArmorType::kHeavyArmor) {
                    associatedSkill = RE::ActorValue::kHeavyArmor;
                }
                else {
                    // If it's clothing or an unknown armor type, default to Pickpocket for skill scaling
                    associatedSkill = RE::ActorValue::kPickpocket;
                }
            }

            // Match item type to user settings
            if (isBackpack) {
                shouldHide = Settings::bUnlootableBackpacks;
                requireWorn = Settings::bBackpacksWornOnly;
                associatedSkill = RE::ActorValue::kPickpocket;
            }
            else if (isWeapon) {
                isSmithable = true;
                shouldHide = Settings::bUnlootableWeapons;
                requireWorn = Settings::bWeaponsWornOnly;

                auto weap = static_cast<RE::TESObjectWEAP*>(a_item);
                switch (weap->GetWeaponType()) {
                case RE::WEAPON_TYPE::kBow:
                case RE::WEAPON_TYPE::kCrossbow:
                    associatedSkill = RE::ActorValue::kArchery;
                    break;
                case RE::WEAPON_TYPE::kTwoHandAxe:
                case RE::WEAPON_TYPE::kTwoHandSword:
                    associatedSkill = RE::ActorValue::kTwoHanded;
                    break;
                default:
                    associatedSkill = RE::ActorValue::kOneHanded;
                    break;
                }
            }
            else if (isAmmo) {
                shouldHide = Settings::bUnlootableAmmo;
                requireWorn = Settings::bAmmoWornOnly;
                associatedSkill = RE::ActorValue::kPickpocket;
            }
            else if (isClothing) {
                shouldHide = Settings::bUnlootableClothing;
                requireWorn = Settings::bClothingWornOnly;
            }
            else if (isJewelry) {
                shouldHide = Settings::bUnlootableJewelry;
                requireWorn = Settings::bJewelryWornOnly;
            }
            else if (isArmor) {
                isSmithable = true;
                if (isShield) {
                    shouldHide = Settings::bUnlootableArmorShield;
                }
                else {
                    if (Settings::bUnlootableArmor) {
                        // Master toggle hides all regular armor
                        shouldHide = true;
                    }
                    else {
                        // Check individual body slots if master toggle is off
                        if (isHead && Settings::bUnlootableArmorHead) shouldHide = true;
                        if (isChest && Settings::bUnlootableArmorChest) shouldHide = true;
                        if (isArms && Settings::bUnlootableArmorArms) shouldHide = true;
                        if (isLegs && Settings::bUnlootableArmorLegs) shouldHide = true;
                    }
                }
                // WornOnly applies to both shields and regular armor
                requireWorn = Settings::bArmorWornOnly;
            }

            // category hide chances
            if (Settings::bUseCategoryHideChances) {
                if (isArmor || isShield) currentHideChance = Settings::fHideChanceArmor;
                else if (isWeapon || isAmmo) currentHideChance = Settings::fHideChanceWeapons;
                else if (isClothing || isJewelry || isBackpack) currentHideChance = Settings::fHideChanceClothing;
            }
        }

        // If the item type isn't configured to be hidden, marked as junk or missing a tool, allow it
        if (!shouldHide && !isJunkItCandidate && !isToolCandidate) return false;

        // From here on, 'a_targetRef' is guaranteed to be a valid owner from history
        auto baseObj = a_targetRef->GetBaseObject();
        if (!baseObj) return false;


        auto actor = a_targetRef->As<RE::Actor>();
        RE::Actor* sourceActor = actor;
        bool isAshGhostCorpseContainer = false;

        if (!actor) {
            // Detect if the target are Ash Piles, Ghost Remains or a custom corpse container
            auto formType = baseObj->GetFormType();
            bool isActivator = (formType == RE::FormType::Activator);
            bool isDynamicContainer = (formType == RE::FormType::Container && (a_targetRef->GetFormID() >> 24) == 0xFF);
            // Specialized handling for non-actor corpse containers/activator (e.g. Ash Piles, FEC Frozen Containers)
            if (isActivator || isDynamicContainer) {
                // Default true for activators (Ash Piles)
                // Default false for 0xFF containers to protect Campfire backpacks and Hearthfire furniture
                isAshGhostCorpseContainer = isActivator;

                // Hardcode fallback for FEC, MaximumCarnage, MaximumDestruction: These mods spawn standalone 0xFF corpse containers without linking them
                if (isDynamicContainer) {
                    auto file = baseObj->GetFile(0);
                    if (file) {
                        const char* fileName = file->GetFilename().data();

                        // If Shadow of Skyrim is detected, all of its various backpack containers are excluded from hiding
                        if (_stricmp(fileName, "Shadow of Skyrim.esp") == 0) {
                            return false;
                        }

                        // If FEC or Maximum Carnage/Destruction are detected, their standalone corpse containers are included to allow hiding their contents
                        if (_stricmp(fileName, "FEC.esp") == 0 || _stricmp(fileName, "MaximumCarnage.esp") == 0 || _stricmp(fileName, "MaximumDestruction.esp") == 0) {
                            isAshGhostCorpseContainer = true;
                        }
                    }
                }

                // Caching the last detected Ash Pile to optimize performance
                static std::unordered_map<RE::FormID, RE::ActorHandle> s_ashPileMap;
                static std::mutex ashPileMutex;

                // Find the original actor that turned into this ash pile
                std::lock_guard<std::mutex> lock(ashPileMutex);
                auto it = s_ashPileMap.find(a_targetRef->GetFormID());
                if (it != s_ashPileMap.end()) {
                    // Check if the handle is valid before getting the actor
                    if (it->second) sourceActor = it->second.get().get();
                }
                else {
                    if (auto processLists = RE::ProcessLists::GetSingleton()) {
                        // Ash Piles don't store their owner directly; scan loaded actors to find who points
                        // to this specific activator as their "ExtraAshPileRef"
                        for (uint32_t i = 0; i < processLists->highActorHandles.size(); ++i) {
                            if (i >= processLists->highActorHandles.size()) break;
                            RE::ActorHandle handle = processLists->highActorHandles[i];
                            if (auto loadedActor = handle.get().get()) {
                                if (auto xAsh = loadedActor->extraList.GetByType<RE::ExtraAshPileRef>()) {
                                    if (xAsh->ashPileRef.get().get() == a_targetRef) {
                                        s_ashPileMap[a_targetRef->GetFormID()] = handle;
                                        sourceActor = loadedActor;
                                        break;
                                    }
                                }
                            }
                        }
                    }
                    if (!sourceActor) s_ashPileMap[a_targetRef->GetFormID()] = RE::ActorHandle();
                    if (s_ashPileMap.size() > 20) s_ashPileMap.clear();
                }

                // If a dead actor explicitly points to this container, it is 100% a corpse!
                if (sourceActor) isAshGhostCorpseContainer = true;
            }
        }

        // Never filter items on living followers, regardless of UI state
        // This should prevent NFF/AFT/EFF framework scripts from being blocked
        if (actor && !actor->IsDead() && !isAshGhostCorpseContainer && actor->IsPlayerTeammate()) return false;

        if (sourceActor) {
            // Check Base-ID whitelist (e.g. Gunjar) to prevent progression blockers
            auto npcBaseID = sourceActor->GetBaseObject()->GetFormID();
            if (std::binary_search(Settings::excludedNPCBaseIDs.begin(), Settings::excludedNPCBaseIDs.end(), npcBaseID)) {
                return false;
            }

            // Check if the actor is a Nemesis from Shadow of Sykrim. Items on NPCs with these keywords will always be visible so the player is able to get them back
            if (sourceActor->HasKeywordString("_Nemesis") || sourceActor->HasKeywordString("_ValidateNemesis")) {
                return false;
            }
        }

        // Check if the actor is in a "knocked out" state (bleeding out or unconscious)
        // This increases potential compatibility with death alternative or knock-out mods 
        // that change the actor's state to incapacitated instead of killing them
        bool isKnockedOut = false;
        if (sourceActor && !sourceActor->IsDead()) {
            auto actorState = sourceActor->AsActorState();
            if (actorState && (actorState->IsBleedingOut() || actorState->IsUnconscious() || actorState->GetLifeState() == RE::ACTOR_LIFE_STATE::kDying)) isKnockedOut = true;
        }

        // Check if the player is currently sneaking
        bool isPlayerSneaking = false;
        if (player) {
            isPlayerSneaking = player->IsSneaking();
        }

        // Determine if the player is attempting to pickpocket the target 
        // (actor is alive, not knocked out, container is open, and player is sneaking)
        bool isPickpocketing = sourceActor && !sourceActor->IsDead() && !isKnockedOut && (a_isContainerOpen || a_isLootMenuOpen) && isPlayerSneaking;

        // Valid target check: The item is eligible for hiding if it's owned by a dead actor, 
        // a knocked-out actor, a specialized corpse container, or via pickpocketing (if enabled)
        bool isValidTarget = (sourceActor && sourceActor->IsDead()) || isKnockedOut || isAshGhostCorpseContainer || (Settings::bIncludePickpocket && isPickpocketing);

        if (isValidTarget) {

            // Early exit if no pickpocketing and all death categories are disabled
            if (!isPickpocketing && !Settings::bApplyToPreDead && !Settings::bApplyToNPCKills && !Settings::bApplyToPlayerKills) {
                return false;
            }

            // If the item is a tool candidate, check if the required tool is missing.
            // Tools are bypassed during pickpocketing and for Ash Piles.
            bool isToolMissing = false;
            if (isToolCandidate && !isPickpocketing && !isAshGhostCorpseContainer) {
                isToolMissing = ToolRequirements::Manager::GetSingleton()->IsToolMissing(a_item, sourceActor);
            }

            // Death category check: Determine the death category and apply category-specific settings
            if (!isPickpocketing) {
                // Fallback logic for orphans
                CorpseCategory category = CorpseCategory::kPlayerKill;

                if (sourceActor && sourceActor->IsDead()) {
                    category = DeathTracker::GetSingleton()->GetCategory(sourceActor);
                }
                else if (isAshGhostCorpseContainer) {
                    if ((a_targetRef->GetFormID() >> 24) == 0xFF) {
                        category = CorpseCategory::kPlayerKill;
                    }
                    else {
                        category = CorpseCategory::kPrePlacedDead;
                    }
                }

                if (category == CorpseCategory::kPrePlacedDead && !Settings::bApplyToPreDead) return false;
                if (category == CorpseCategory::kNPCKill && !Settings::bApplyToNPCKills) return false;
                if (category == CorpseCategory::kPlayerKill && !Settings::bApplyToPlayerKills) return false;
            }

            bool isQuestObject = false;
            bool isWorn = false;
            bool isExtraEnchanted = false;
            bool isPlayerModified = false;
            bool foundInNPCInventory = false;
            bool confirmedJunkIt = false;

            RE::TESObjectREFR* inventoryOwner = sourceActor ? sourceActor : a_targetRef;

			// Directly check the inventory entry data provided by QuickLoot
            if (a_entryData) {
                foundInNPCInventory = true;

                // Junk It detection for items marked as junk
                if (Settings::bHideJunkItItems && JunkIt::API && JunkIt::API->IsJunk(a_entryData)) {
                    confirmedJunkIt = true;
                }

                if (a_entryData->IsQuestObject()) isQuestObject = true;
                if (a_entryData->IsWorn()) isWorn = true;
                // Check for individual enchanted items in the inventory if the setting is enabled
                if (a_entryData->IsEnchanted() && Settings::bAlwaysShowEnchanted) isExtraEnchanted = true;

                // If the item has been modified by the player it should be considered as "player-owned" and not hidden
                if (Settings::bProtectPlayerModifiedGear && a_entryData->extraLists) {
                    for (auto* xList : *a_entryData->extraLists) {
                        if (xList && (xList->HasType(RE::ExtraDataType::kTextDisplayData) ||
                            xList->HasType(RE::ExtraDataType::kEnchantment) ||
                            (!Settings::bIgnoreHealthExtraData && xList->HasType(RE::ExtraDataType::kHealth)))) {
                            isPlayerModified = true;
                            break;
                        }
                    }
                }
            }
            else {
				// Now fetch dynamic changes (like Worn or Player Modified) if they exist yet
                auto changes = inventoryOwner->GetInventoryChanges();
                if (changes && changes->entryList) {
                    for (auto* entry : *changes->entryList) {
                        if (entry && entry->object && entry->object->GetFormID() == a_item->GetFormID()) {
                            if (Settings::bHideJunkItItems && JunkIt::API && JunkIt::API->IsJunk(entry)) {
                                confirmedJunkIt = true;
                            }
                            if (entry->IsQuestObject()) isQuestObject = true;
                            if (entry->IsWorn()) isWorn = true;
                            if (entry->IsEnchanted() && Settings::bAlwaysShowEnchanted) isExtraEnchanted = true;

                            if (Settings::bProtectPlayerModifiedGear && entry->extraLists) {
                                for (auto* xList : *entry->extraLists) {
                                    if (xList && (xList->HasType(RE::ExtraDataType::kTextDisplayData) ||
                                        xList->HasType(RE::ExtraDataType::kEnchantment) ||
                                        (!Settings::bIgnoreHealthExtraData && xList->HasType(RE::ExtraDataType::kHealth)))) {
                                        isPlayerModified = true;
                                        break;
                                    }
                                }
                            }
                            break;
                        }
                    }
                }
                // Fallback for fresh corpses: If no dynamic changes exist, but it's a Junk It candidate, confirm it.
                if (isJunkItCandidate && !confirmedJunkIt) {
                    confirmedJunkIt = true;
                }
            }

            // If the item is naturally allowed, not confirmed as junk, and no tool is missing, allow it
            if (!shouldHide && !isToolMissing && !confirmedJunkIt) {
                return false;
            }
            
            // Safety: Never hide Quest Items, specifically whitelisted enchanted gear or player-modified items (e.g. via tempering or enchanting)
            if (isQuestObject || isExtraEnchanted || isPlayerModified)  return false;

            // If the item is missing a required tool, hide it
            if (isToolMissing) {
                return true;
            }

            // If the item is confirmed as junk, hide it
            if (confirmedJunkIt) {
                return true;
            }

            // skill hide chance reduction
            if (Settings::bEnableSkillScaling && isPlayerLoaded && currentHideChance > 0.0f) {
                float totalReduction = 0.0f;

                if (auto avOwner = player->AsActorValueOwner()) {
                    if (associatedSkill != RE::ActorValue::kNone && Settings::fMaxSkillHideReduction > 0.0f) {
                        float skillLevel = avOwner->GetActorValue(associatedSkill);
                        totalReduction += (std::clamp(skillLevel, 0.0f, 100.0f) / 100.0f) * Settings::fMaxSkillHideReduction;
                    }
                    if (isSmithable && Settings::fMaxSmithingHideReduction > 0.0f) {
                        float smithingLevel = avOwner->GetActorValue(RE::ActorValue::kSmithing);
                        totalReduction += (std::clamp(smithingLevel, 0.0f, 100.0f) / 100.0f) * Settings::fMaxSmithingHideReduction;
                    }
                }

                if (totalReduction > 0.0f) {
                    currentHideChance -= totalReduction;
                    if (currentHideChance < 0.0f) currentHideChance = 0.0f;
                }
            }


            // Apply deterministic 'random' hiding based on the actor-item seed
            if (currentHideChance < 100.0f) {
                uint32_t seed = a_targetRef->GetFormID() ^ a_item->GetFormID();

                seed = (seed ^ 61) ^ (seed >> 16);
                seed = seed + (seed << 3);
                seed = seed ^ (seed >> 4);
                seed = seed * 0x27d4eb2d;
                seed = seed ^ (seed >> 15);

                float randomVal = static_cast<float>(seed % 10000) / 100.0f;
                if (randomVal >= currentHideChance) return false;
            }

            // Final decision based on 'WornOnly' setting
            if (actor && requireWorn && !isAshGhostCorpseContainer) {
                // Hide only if worn
                if (isWorn) return true;
            }
            else if (isAshGhostCorpseContainer) {
                // Specialized containers lose the 'isWorn' flag, so hide them forcefully if hiding is enabled
                return true;
            }
            else return true;
        }
        return false;
    }

    // QuickLoot API Handler: Filters the actual inventory array before QuickLoot renders it
    void HandleQuickLootInventory(QuickLoot::API::Events::ModifyInventoryEvent* a_event) {
        if (!Settings::bEnableMod || !a_event) return;

        auto containerRef = a_event->container.get().get();
        if (!containerRef) return;

		// Iterate backwards because elements from the array are being removed
        for (int i = static_cast<int>(a_event->inventory.size()) - 1; i >= 0; --i) {
            auto& stack = a_event->inventory[i];
            if (stack.entry && stack.entry->object) {

                bool hide = ShouldHideItem(stack.entry->object, containerRef, false, true, stack.entry);

                if (hide) {
                    delete stack.entry;
                    a_event->inventory.erase(a_event->inventory.begin() + i);
                }
            }
        }
    }

    // Core logic to determine if an item should be shown or hidden
    bool ProcessItem(RE::TESBoundObject* a_this, bool originalResult)
    {
        // Abort if mod is disabled or the item is natively unplayable
        if (!Settings::bEnableMod) return originalResult;
        if (!originalResult) return false;

        auto ui = RE::UI::GetSingleton();
        if (!ui) return true;

        // UI Context check
        if (ui->IsMenuOpen(RE::InventoryMenu::MENU_NAME) ||
            ui->IsMenuOpen(RE::MagicMenu::MENU_NAME) ||
            ui->IsMenuOpen(RE::FavoritesMenu::MENU_NAME) ||
            ui->IsMenuOpen(RE::BarterMenu::MENU_NAME) ||
            ui->IsMenuOpen(RE::CraftingMenu::MENU_NAME) ||
            ui->IsMenuOpen(RE::GiftMenu::MENU_NAME)) {
            return true;
        }

        // Check if the ContainerMenu exists in memory (covers opening phase before IsMenuOpen is true)
        auto menu = ui->GetMenu(RE::ContainerMenu::MENU_NAME);
        bool isContainerOpen = menu.get() != nullptr;

        RE::TESObjectREFR* targetRef = nullptr;

        if (isContainerOpen) {
            // Directly ask the menu which container is beeing looted
            auto containerMenu = static_cast<RE::ContainerMenu*>(menu.get());
            if (containerMenu) {
                auto handle = containerMenu->GetTargetRefHandle();
                RE::NiPointer<RE::TESObjectREFR> refPtr;
                if (RE::TESObjectREFR::LookupByHandle(handle, refPtr)) {
                    RE::TESObjectREFR* lootTarget = refPtr.get();
                    if (lootTarget) {
                        auto base = lootTarget->GetBaseObject();
                        bool isSpecial = base && (base->Is(RE::FormType::Activator) || (base->Is(RE::FormType::Container) && (lootTarget->GetFormID() >> 24) == 0xFF));

                        bool corpseHasItem = ContainerHasItem(lootTarget, a_this, isSpecial);

                        // Protect the player's inventory from being hidden when the ContainerMenu is open
                        // If the player owns this item, it always gets shown
                        auto player = RE::PlayerCharacter::GetSingleton();
                        bool playerHasItem = player && player->Is3DLoaded() && ContainerHasItem(player, a_this, false);

                        if (!corpseHasItem && playerHasItem) {
                            return true;
                        }

                        targetRef = lootTarget;
                    }
                }
            }
        }
        else {
            targetRef = GetCrosshairTarget(a_this);
        }
        
        // If there's still no target, show the item as a failsafe
        if (!targetRef) {
            return true;
        }

        // Send to central logic (Invert result since ShouldHideItem returns true when an item should be hidden)
        return !ShouldHideItem(a_this, targetRef, isContainerOpen, false);
    }

    bool Hook_ARMO_GetPlayable(RE::TESObjectARMO* a_this) {
        return ProcessItem(a_this, original_ARMO_GetPlayable(a_this));
    }

    bool Hook_WEAP_GetPlayable(RE::TESObjectWEAP* a_this) {
        return ProcessItem(a_this, original_WEAP_GetPlayable(a_this));
    }

    bool Hook_MISC_GetPlayable(RE::TESObjectMISC* a_this) {
        return ProcessItem(a_this, original_MISC_GetPlayable(a_this));
    }

    bool Hook_ALCH_GetPlayable(RE::AlchemyItem* a_this) {
        return ProcessItem(a_this, original_ALCH_GetPlayable(a_this));
    }

    bool Hook_INGR_GetPlayable(RE::IngredientItem* a_this) {
        return ProcessItem(a_this, original_INGR_GetPlayable(a_this));
    }

    bool Hook_BOOK_GetPlayable(RE::TESObjectBOOK* a_this) {
        return ProcessItem(a_this, original_BOOK_GetPlayable(a_this));
    }

    bool Hook_SCRL_GetPlayable(RE::ScrollItem* a_this) {
        return ProcessItem(a_this, original_SCRL_GetPlayable(a_this));
    }

    bool Hook_AMMO_GetPlayable(RE::TESAmmo* a_this) {
        return ProcessItem(a_this, original_AMMO_GetPlayable(a_this));
    }

    void InstallHooks()
    {
        // Hook GetPlayable for Armors
        REL::Relocation<std::uintptr_t> armoVTable(RE::VTABLE_TESObjectARMO[0]);
        original_ARMO_GetPlayable = armoVTable.write_vfunc(0x19, reinterpret_cast<std::uintptr_t>(Hook_ARMO_GetPlayable));

        // Hook GetPlayable for Weapons
        REL::Relocation<std::uintptr_t> weapVTable(RE::VTABLE_TESObjectWEAP[0]);
        original_WEAP_GetPlayable = weapVTable.write_vfunc(0x19, reinterpret_cast<std::uintptr_t>(Hook_WEAP_GetPlayable));
        
        // Hook GetPlayable for MISC
        REL::Relocation<std::uintptr_t> miscVTable(RE::VTABLE_TESObjectMISC[0]);
        original_MISC_GetPlayable = miscVTable.write_vfunc(0x19, reinterpret_cast<std::uintptr_t>(Hook_MISC_GetPlayable));

        // Hook GetPlayable for ALCH (Food, Poison and Potions)
        REL::Relocation<std::uintptr_t> alchVTable(RE::VTABLE_AlchemyItem[0]);
        original_ALCH_GetPlayable = alchVTable.write_vfunc(0x19, reinterpret_cast<std::uintptr_t>(Hook_ALCH_GetPlayable));

        // Hook GetPlayable for INGR (Ingredients)
        REL::Relocation<std::uintptr_t> ingrVTable(RE::VTABLE_IngredientItem[0]);
        original_INGR_GetPlayable = ingrVTable.write_vfunc(0x19, reinterpret_cast<std::uintptr_t>(Hook_INGR_GetPlayable));

        // Hook GetPlayable for BOOK (Books, Notes and Journals)
        REL::Relocation<std::uintptr_t> bookVTable(RE::VTABLE_TESObjectBOOK[0]);
        original_BOOK_GetPlayable = bookVTable.write_vfunc(0x19, reinterpret_cast<std::uintptr_t>(Hook_BOOK_GetPlayable));

        // Hook GetPlayable for SCRL (Scrolls)
        REL::Relocation<std::uintptr_t> scrlVTable(RE::VTABLE_ScrollItem[0]);
        original_SCRL_GetPlayable = scrlVTable.write_vfunc(0x19, reinterpret_cast<std::uintptr_t>(Hook_SCRL_GetPlayable));

        // Hook GetPlayable for AMMO (Arrows & Bolts)
        REL::Relocation<std::uintptr_t> ammoVTable(RE::VTABLE_TESAmmo[0]);
        original_AMMO_GetPlayable = ammoVTable.write_vfunc(0x19, reinterpret_cast<std::uintptr_t>(Hook_AMMO_GetPlayable));

        logs::info("VTable hooks applied successfully.");
    }
}